### ISSUE TITLE
CXX - 11 problems

### ISSUE THREAD

**Issue by Ktysai** [paul-shuvo/iai_kinect2_opencv4#1]
Hi Paul!

I've used your fork in order to use Kinect v2 on Noetic Ubuntu 20.04.

Still I've got CXX 11 related errors. I've manage to solve them , but you've had them also?

**Comment by paul-shuvo** [comment]
Hey Ktysai,

I remember having issues with opencv4 and that's why I have this repo. I think CXX issues are part of the kinect driver/ library dependency. Could you share the error you were having so that I could take a look?
